### ISSUE TITLE
Problemas con agruparGastos

### ISSUE THREAD

**Issue by BCivieta** [BCivieta/practica_dwec_gestor_presupuesto#1]
@pedroprieto me he quedado atascada en la funcion de agruparGastos, no pasa el test y no consigo entender por que, no se si es problema de la funcion filtrarGastos... pero esta si pasa el test. Si pudieras echarme una mano. En mi ultimo push estan todos los cambios, tengo que hacerte una pull para que puedas verlos?
Muchas gracias!

**Comment by pedroprieto** [comment]
Buenas,

No hace falta PR, puedo ver el código en tu repositorio.

El problema está en esta línea:
https://github.com/BCivieta/practica_dwec_gestor_presupuesto/blob/3c88ed1326477d808aac463c54ecf1721ea92149/js/gestionPresupuesto.js#L195

El orden de los parámetros es incorrecto: el segundo parámetro debe ser `etiquetas`.

Un saludo!
