### ISSUE TITLE
Problemas en Interacción con HTML

### ISSUE THREAD

**Issue by BCivieta** [BCivieta/practica_dwec_gestor_presupuesto#2]
Buenas @pedroprieto,  no se por qué la práctica no pasa ni el primer test, ayuda por favor!

**Comment by pedroprieto** [comment]
Tienes un error: pone `scr` y es `src`:
https://github.com/BCivieta/practica_dwec_gestor_presupuesto/blob/da0b443909d622a17643c2b2accaa96c838cdae4/interaccionHTML.html#L44

Y aquí, redeclaras `idElemento`, que es el parámetro de la función. Debes elegir otro nombre:
https://github.com/BCivieta/practica_dwec_gestor_presupuesto/blob/da0b443909d622a17643c2b2accaa96c838cdae4/js/gestionPresupuestoWeb.js#L4

Un saludo!
