### ISSUE TITLE
Más problemas con interaccionHTML :(

### ISSUE THREAD

**Issue by BCivieta** [BCivieta/practica_dwec_gestor_presupuesto#3]
@pedroprieto Gracias por la ayda anterior, a veces me vuelvo ciega y no soy capaz de ver... llevo un rato mirando el codigo y no consigo saber que le pasa al filtrado2, se supone que si pasa los test de la práctica tres, la funcion filtrar está ok, si pasa el primer test de esta práctica la función mostrar gasto web está ok, con lo cual el error está aquí: ?
for(let gasto of gesPres.filtrarGastos({ ValorMinimo: 50 })){
    gesPresWeb.mostrarGastoWeb("listado-gastos-filtrado-2", gasto);
}
El resto de flitros no los pasa porque tiene que pasar este primero si o si o es que tambien están mal??
gracias!

**Comment by pedroprieto** [comment]
Buenas,

https://github.com/BCivieta/practica_dwec_gestor_presupuesto/blob/ac2e64c49d58e0f1d64612b4c6a719b3da985ff4/js/generarDatosEstaticos.js#L32

La función de filtrar espera `valorMInimo`, con la `v` minúscula:
https://github.com/BCivieta/practica_dwec_gestor_presupuesto/blob/ac2e64c49d58e0f1d64612b4c6a719b3da985ff4/js/gestionPresupuesto.js#L170

Un saludo!

**Comment by BCivieta** [comment]
Mader mia...Ciega es poco!!
gracias!
