### ISSUE TITLE
Olvido pull practica fundamentos JSIII

### ISSUE THREAD

**Issue by BCivieta** [BCivieta/practica_dwec_gestor_presupuesto#4]
@pedroprieto creo que no te hice la pull para el tema de JSIII, pero no estoy segura, he visto que en esa práctica no me has puesto nota,  y no recuerdo la pull requests, que hago?

**Comment by pedroprieto** [comment]
No pasa nada. Solo se puede tener una PR abierta. Cuando vayas a entregar la de Interacción, ponme también que entregas la de fundamentos III.

Un saludo!

**Comment by BCivieta** [comment]
Es que ya he entregado la de interacción, me he dado cuenta después de entregarla justo, que no me sonaba haberlo hecho con fundamentos JSIII.Puedo ponertelo en la de eventos que es la que estoy haciendo ahora, al terminar te hago alguna referncia a ello...o te hago una pull ahora y te pongo que es para fundamentosJSIII( aunque eventos este a medias). lo que me digas!
Un saludo y gracias!

**Comment by pedroprieto** [comment]
No te preocupes, acabo de revisarte el código. Está todo bien, así que te la califico en Aules ahora mismo. Bien hecho! :clap:
